version: "3.8"
services:
  logger:
    stdin_open: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Phoenix.Dockerfile
    working_dir: /loggex
    command: bash
    volumes:
      - .:/loggex:cached
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=ecto://rdb:postgres@postgres/dev_db
    links:
      - rdb
    ports:
      - "4000:4000"
  rdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
